name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependency Packages
        run: npm i

      - name: Build
        run: npm run build